captcha:
  active: true
  type: 2
   #Types: 1 = head, 2 = item

stafflogin:
  active: true
  discordtoken: 'NTk0MDE5MzA1NTQ1MjY5MjYw.Xq5aFQ.-D7-_T2J-kbsB_BQbZ27uxSVcLo'


# Bypass Captcha Permission: jlogin.staff.cbypass
# Account Command Permission: jlogin.command.account
