captcha:
  active: false
  type: 2
   #Types: 1 = head, 2 = item

stafflogin:
  active: false
  discordtoken: 'TOKEN DO BOT'


# Bypass Captcha Permission: jlogin.captcha.bypass
# Account Command Permission: jlogin.command.account
# Login Staff Command Permission: jlogin.staff.login
# Staff Login Command Permission: jlogin.command.owner


