captcha:
  active: true
  type: 2
   #Types: 1 = head, 2 = item

stafflogin:
  active: false
  discordtoken: 'DISCORD BOT TOKEN'

# Capcha Bypass Permission: jlogin.capcha.bypass
# Account Command Permission: jlogin.command.account
# Login Staff Command Permission: jlogin.staff.login
# Staff Login Command Permission: jlogin.command.owner


