name: JVLogin
version: 1.0-SNAPSHOT
main: net.jvinicius.login.v1.principal.MainClass
author: JVinicius
website: https://jvinicius.net
commands:
  login:
  register:
  changepwd:
  accountcheck:
  stafflogin:
  loginstaff: